#!/bin/bash

INPUT=$1
OUTPUT=$1.svg

echo '<?xml version="1.0" encoding="utf-8"?>' >$OUTPUT
echo '<svg xmlns="http://www.w3.org/2000/svg">' >>$OUTPUT
sed s/svg/symbol/g $INPUT/*.svg >>$OUTPUT
echo '</svg>' >>$OUTPUT
